#ifndef DEFINE_H
#define DEFINE_H

#define VALIDATIONNUMBER 0x5678

#define VERSION_COMMUNICATION 1
#define VERSION_SERVERLIST 1
#define VERSION_STRING "1.0.0"

#define ACTION_GETINFO 0
#define ACTION_CONNECT 1
#define ACTION_REGISTER 2

#define NETWORK_ERROR_VERSION 99
#define NETWORK_OK 88

#define AUTHMODE_NONE 0
#define AUTHMODE_PASSWORD 1
#define AUTHMODE_USERANDPASSWORD 2

#define CONNECT_ERROR_AUTHMODE 100
#define CONNECT_ERROR_PASSWORD 101
#define CONNECT_OK 1

#define REGISTER_ERROR_NOTALLOW 100
#define REGISTER_ERROR_DUPLICATION 101
#define REGISTER_OK 1

#define SERVER_RECONNECT 100
#define SERVER_CHOOSEROOM 101

#define ROOM_JOIN 1
#define ROOM_JOIN_ERROR_INVALID 11
#define ROOM_JOIN_ERROR_FULL 12
#define ROOM_JOIN_ERROR_CANONLOOK 14
#define ROOM_JOIN_OK 13
#define ROOM_CREATE 2
#define ROOM_CREATE_OK 21
#define ROOM_CREATE_ERROR_FULL 22
#define ROOM_ONLOOK 3
#define ROOM_ONLOOK_ERROR_INVALID 31
#define ROOM_ONLOOK_ERROR_FULL 32
#define ROOM_ONLOOK_OK 33
#define ROOM_FIND 4
#define ROOM_FIND_ERROR 41
#define ROOM_FIND_OK 42
#define ROOM_PAGE_FIRST 51
#define ROOM_PAGE_PREV 52
#define ROOM_PAGE_NEXT 53
#define ROOM_PAGE_LAST 54
#define ROOM_PAGE_ERROR 55
#define ROOM_PAGE_OK 56
#define ROOM_REFRESH 6
#define ROOM_REFRESH_OK 62

#define URL_DEFAULTGET "http://fairsgs.tk/"
#define URL_DEFAULTREG "http://fairsgs.sinaapp.com/"

#define GENERALPACKAGE_FENG 0
#define GENERALPACKAGE_HUO 1
#define GENERALPACKAGE_LIN 2
#define GENERALPACKAGE_SHAN 3
#define GENERALPACKAGE_YIJIANG 4
#define GENERALPACKAGE_YIJIANG2012 5
#define GENERALPACKAGE_YIJIANG2013 6
#define GENERALPACKAGE_YIJIANG2014 7
#define GENERALPACKAGE_SP 8
#define GENERALPACKAGE_XINGSP 9
#define GENERALPACKAGE_OL 10
#define GENERALPACKAGE_JIEXIANTUPO 11

#define SHENMODE_BAN 0
#define SHENMODE_DEFAULT 1
#define SHENMODE_CUSTOM 2

#define SOCKETSTATE_INIT 0
#define SOCKETSTATE_VARIFIED 1
#define SOCKETSTATE_CONNECTED 2
#define SOCKETSTATE_CHOOSEROOM 3
#define SOCKETSTATE_PLAYER 10
#define SOCKETSTATE_ONLOOKER 11
#define SOCKETSTATE_PLAYING 100
#define SOCKETSTATE_GOINGTODIE -1

#define CLIENTSTATE_INIT 0
#define CLIENTSTATE_CONNECTED 1
#define CLIENTSTATE_INSERVER 2
#define CLIENTSTATE_CHOOSEROOM 3
#define CLIENTSTATE_ENTERROOM 4
#define CLIENTSTATE_ONLOOKROOM 5
#define CLIENTSTATE_INROOM 6

#define MAX_GENERAL 27

#define ROLE_ZHU 0
#define ROLE_ZHONG 1
#define ROLE_FAN 2
#define ROLE_NEI 3
#define ROLE_UNKNOWN 4

#define PLAYERSTATE_INIT 0

#define ROOMPLAYER_HOST 1
#define ROOMPLAYER_ADMIN 2

#define INROOM_NEWPLAYER 1

#endif // DEFINE_H

