#ifndef DEFINE_H
#define DEFINE_H

#define VALIDATIONNUMBER 0x5678

#define VERSION_COMMUNICATION 0
#define VERSION_SERVERLIST 1
#define VERSION_STRING "1.0.0"

#define ACTION_GETINFO 0
#define ACTION_CONNECT 1
#define ACTION_REGISTER 2

#define NETWORK_ERROR_VERSION 99
#define NETWORK_OK 88

#define AUTHMODE_NONE 0
#define AUTHMODE_PASSWORD 1
#define AUTHMODE_USERANDPASSWORD 2

#define CONNECT_ERROR_AUTHMODE 100
#define CONNECT_ERROR_PASSWORD 101
#define CONNECT_OK 0

#define REGISTER_ERROR_NOTALLOW 100
#define REGISTER_ERROR_DUPLICATION 101
#define REGISTER_OK 0

#define SERVER_RECONNECT 0
#define SERVER_ENTERROOM 1
#define SERVER_CHOOSEROOM 2

#define URL_DEFAULTGET "http://fairsgs.tk/"
#define URL_DEFAULTREG "http://fairsgs.sinaapp.com/"

#define GENERALPACKAGE_FENG 0
#define GENERALPACKAGE_HUO 1
#define GENERALPACKAGE_LIN 2
#define GENERALPACKAGE_SHAN 3
#define GENERALPACKAGE_YIJIANG 4
#define GENERALPACKAGE_YIJIANG2012 5
#define GENERALPACKAGE_YIJIANG2013 6
#define GENERALPACKAGE_YIJIANG2014 7
#define GENERALPACKAGE_SP 8
#define GENERALPACKAGE_XINGSP 9
#define GENERALPACKAGE_OL 10
#define GENERALPACKAGE_JIEXIANTUPO 11

#define SHENMODE_BAN 0
#define SHENMODE_DEFAULT 1
#define SHENMODE_CUSTOM 2

#define SOCKETSTATE_INIT 0
#define SOCKETSTATE_VARIFIED 1
#define SOCKETSTATE_CONNECTED 2
#define SOCKETSTATE_GOINGTODIE -1

#endif // DEFINE_H

